### ISSUE TITLE
Problem with API after upgrading to v3.0.6 from v3.0.4

### ISSUE THREAD

**Issue by xReveres** [Iridium-Development/IridiumSkyblock#276]
I'm using IridiumSkyblockAPI to create custom island command. On IridiumSkyblock v.3.0.4 everythink works fine, but after upgrading to v.3.0.6 my plugin crashes.

> java.lang.NoSuchMethodError: com.iridium.iridiumskyblock.commands.Command.<init>(Ljava/util/List;Ljava/lang/String;Ljava/lang/String;Z)V

**Comment by xReveres** [comment]
Hmm, on
https://nexus.savagelabs.net/#browse/search=keyword%3DIridiumSkyblock
I see only v.3.0.4.

**Comment by dlsf** [comment]
That's because the `Command#onCommand()` now has to return a boolean and the Command constructor changed.

But @PeachesMLG should update the dependency, that's correct.

**Comment by MertUnverdi** [comment]
@PeachesMLG don't forgot it 😡

**Comment by xReveres** [comment]
@dlsf Thanks. 
@PeachesMLG 
It's really important for me (our server) to keep API updated, every time when new plugin version shows up thanks to that we can extend many things in IridiumSkyblock.

**Comment by PeachesMLG** [comment]
done
